<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
  <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>HRSystem.Web</AssemblyName>
    <RootNamespace>HRSystem.Web</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FrameworkX.Common\FrameworkX.Common.csproj" />
    <ProjectReference Include="..\HRSystem.Domain\HRSystem.Domain.csproj" />
  </ItemGroup>

</Project>