<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>HRSystem.Domain</AssemblyName>
    <RootNamespace>HRSystem.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.4.4" />
    <PackageReference Include="EntityFramework.SqlServer" Version="6.4.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FrameworkX.Common\FrameworkX.Common.csproj" />
  </ItemGroup>

</Project>